/**
 * Demo observations — the Scan Inbox layer.
 *
 * Statuses are mixed deliberately: six promoted (each pointing at the signal
 * it became), two archived as noise with explicit triage rationales for the
 * Noise Filter panel, one parked for more evidence, one duplicate, and six
 * still unreviewed. Checklists are filled consistently with each status.
 */

import type { Observation } from "../types";

export const seedObservations: Observation[] = [
  // --- promoted ------------------------------------------------------------
  {
    id: "OBS-001",
    title: "Independent Gulf menswear labels re-cutting the thobe for daily wear",
    description:
      "Across September 2025 the TikTok creator panel repeatedly surfaced small Dubai- and Riyadh-based menswear labels releasing thobes and bishts re-cut in technical fabrics, with shortened hems, hidden plackets and sneaker-first styling. Creators framed the pieces as everyday wear rather than occasion dress, and several drops sold out within days.",
    sourceId: "SRC-006",
    sourceName: "Regional TikTok fashion and lifestyle creators (demo panel)",
    sourceUrl: null,
    sourceType: "social_media",
    dateObserved: "2025-09-29",
    eventDate: "2025-09-20",
    region: "GCC",
    country: "UAE",
    city: "Dubai",
    sectors: ["fashion_luxury", "culture_arts_heritage"],
    subsector: "menswear / contemporary heritage design",
    actorInvolved: "Independent regional menswear labels (demo)",
    initialNotes:
      "Not a costume revival — the design language is contemporary and the price point sits between streetwear and entry luxury. Multiple labels moving at once, and a culture magazine has since profiled two of them.",
    potentialFutureRelevance:
      "If heritage garments become a living design category rather than ceremonial dress, regional identity becomes a commercial design input across fashion, retail and media.",
    status: "promoted",
    triageRationale: null,
    checklist: {
      behaviourShift: true,
      systemShift: false,
      surprising: true,
      widerRegionalIssue: true,
      credibleSource: false,
      futureImplications: true,
      connectedToOthers: true,
      revealsTension: true,
      earlyButMeaningful: true,
    },
    promotedSignalId: "SIG-001",
    createdAt: "2025-09-29T10:15:00.000Z",
    updatedAt: "2025-10-06T08:40:00.000Z",
  },
  {
    id: "OBS-002",
    title: "Gulf resort operator announces in-house longevity clinic with diagnostics",
    description:
      "A regional hotel and wellness operator announced a longevity clinic inside a flagship Dubai resort: full-body diagnostic screening, biomarker panels and physician-led programmes sold as multi-day packages. The release positions the clinic as a permanent facility, not a seasonal retreat, and names a second property in Riyadh for 2026.",
    sourceId: "SRC-009",
    sourceName: "Press releases from a Gulf hotel and wellness operator (demo)",
    sourceUrl: null,
    sourceType: "company_announcement",
    dateObserved: "2026-01-14",
    eventDate: "2026-01-12",
    region: "UAE",
    country: "UAE",
    city: "Dubai",
    sectors: ["hospitality_tourism", "health_wellness_longevity"],
    subsector: "wellness & longevity",
    actorInvolved: "Gulf hotel and wellness operator (demo)",
    initialNotes:
      "Third such announcement logged since November; the trade press reports two more operators scoping clinical partners. PR-heavy source, but the pattern of capital allocation is real.",
    potentialFutureRelevance:
      "Hotels adding clinical infrastructure blur hospitality and healthcare, and give the Gulf a claim on the fly-in longevity market currently served by Switzerland and Southeast Asia.",
    status: "promoted",
    triageRationale: null,
    checklist: {
      behaviourShift: true,
      systemShift: true,
      surprising: true,
      widerRegionalIssue: true,
      credibleSource: false,
      futureImplications: true,
      connectedToOthers: true,
      revealsTension: false,
      earlyButMeaningful: true,
    },
    promotedSignalId: "SIG-002",
    createdAt: "2026-01-14T09:05:00.000Z",
    updatedAt: "2026-01-20T11:30:00.000Z",
  },
  {
    id: "OBS-003",
    title: "School waiting lists lengthening in Dubai family districts amid golden-visa relocations",
    description:
      "Newspaper reporting, corroborated by school-group statements, describes waiting lists at mid-fee British- and Indian-curriculum schools in Dubai's family districts, attributed to households relocating on 10-year golden visas. Agents report three-bedroom lease renewals rising and families negotiating longer tenancies.",
    sourceId: "SRC-004",
    sourceName: "Gulf economics desk of an international newspaper (demo)",
    sourceUrl: null,
    sourceType: "news_publication",
    dateObserved: "2025-10-27",
    eventDate: "2025-10-20",
    region: "UAE",
    country: "UAE",
    city: "Dubai",
    sectors: ["migration_citizenship_belonging", "real_estate_urban", "education_work"],
    subsector: "long-term residency",
    actorInvolved: "Relocating families on long-term visas (demo)",
    initialNotes:
      "The interesting unit is the family, not the worker. Schooling and multi-year tenancy decisions are commitments a transient expatriate model does not produce.",
    potentialFutureRelevance:
      "Residency policy is converting a rotation-based expatriate market into a settlement market — with structural consequences for housing mix, schooling capacity and household finance.",
    status: "promoted",
    triageRationale: null,
    checklist: {
      behaviourShift: true,
      systemShift: true,
      surprising: false,
      widerRegionalIssue: true,
      credibleSource: true,
      futureImplications: true,
      connectedToOthers: true,
      revealsTension: true,
      earlyButMeaningful: true,
    },
    promotedSignalId: "SIG-003",
    createdAt: "2025-10-27T07:50:00.000Z",
    updatedAt: "2025-11-05T09:10:00.000Z",
  },
  {
    id: "OBS-004",
    title: "Bank equity note flags AI service rollouts — and a spike in verification complaints",
    description:
      "A regional investment-bank note on Gulf retail banks highlights aggressive deployment of AI assistants and automated credit decisioning, then flags an unexpected datapoint: rising branch appointment bookings and complaint volumes from customers asking for human confirmation of AI-made decisions, echoed in youth survey verbatims.",
    sourceId: "SRC-013",
    sourceName: "Gulf banking sector note from a regional investment bank (demo)",
    sourceUrl: null,
    sourceType: "financial_research",
    dateObserved: "2026-03-02",
    eventDate: "2026-02-25",
    region: "GCC",
    country: "UAE",
    city: null,
    sectors: ["technology_ai", "finance_banking_investment"],
    subsector: "retail banking automation",
    actorInvolved: "Gulf retail banks (demo)",
    initialNotes:
      "The automation is expected; the countercurrent is not. Customers are not rejecting AI — they are demanding a human layer on top of it. That is a product gap, not a resistance story.",
    potentialFutureRelevance:
      "If verification demand persists, 'a human will confirm this' becomes a sellable service tier across banking, insurance and government services.",
    status: "promoted",
    triageRationale: null,
    checklist: {
      behaviourShift: true,
      systemShift: true,
      surprising: true,
      widerRegionalIssue: true,
      credibleSource: true,
      futureImplications: true,
      connectedToOthers: true,
      revealsTension: true,
      earlyButMeaningful: true,
    },
    promotedSignalId: "SIG-006",
    createdAt: "2026-03-02T13:25:00.000Z",
    updatedAt: "2026-03-09T10:00:00.000Z",
  },
  {
    id: "OBS-005",
    title: "Field notes: Riyadh specialty coffee houses functioning as evening civic rooms",
    description:
      "Across six observation visits in Riyadh and Jeddah, specialty coffee houses were consistently full from 20:00 to past midnight with mixed groups studying, running book clubs, holding small business meetings and hosting informal majlis-style gatherings. Several venues now programme events and reserve tables for recurring groups.",
    sourceId: "SRC-012",
    sourceName: "Analyst field notes from Riyadh and Jeddah coffee districts (demo)",
    sourceUrl: null,
    sourceType: "ethnographic_observation",
    dateObserved: "2025-10-16",
    eventDate: null,
    region: "Saudi Arabia",
    country: "Saudi Arabia",
    city: "Riyadh",
    sectors: ["food_beverage_third_places", "culture_arts_heritage"],
    subsector: "specialty coffee / third places",
    actorInvolved: "Independent specialty coffee houses (demo)",
    initialNotes:
      "The venues behave like community infrastructure, not F&B outlets: repeat groups, programming, long dwell times, low table turnover tolerated by operators. Cultural producer interview confirms venues are becoming default meeting infrastructure for young creatives.",
    potentialFutureRelevance:
      "Youth third places are forming ahead of formal civic infrastructure — whoever hosts them shapes community, taste and spending patterns for a decade.",
    status: "promoted",
    triageRationale: null,
    checklist: {
      behaviourShift: true,
      systemShift: true,
      surprising: false,
      widerRegionalIssue: true,
      credibleSource: false,
      futureImplications: true,
      connectedToOthers: true,
      revealsTension: false,
      earlyButMeaningful: true,
    },
    promotedSignalId: "SIG-008",
    createdAt: "2025-10-16T18:45:00.000Z",
    updatedAt: "2025-10-19T09:30:00.000Z",
  },
  {
    id: "OBS-006",
    title: "Youth survey shows BNPL as default checkout choice; regulator signals licensing tightening",
    description:
      "The quarterly GCC youth survey reports a majority of 18–30 respondents in Saudi Arabia using buy-now-pay-later at least monthly, with a growing share carrying three or more concurrent plans. In the same fortnight, central-bank commentary reported by the financial press signalled tighter licensing and affordability rules for instalment providers.",
    sourceId: "SRC-011",
    sourceName: "GCC youth financial habits survey by a regional research house (demo)",
    sourceUrl: null,
    sourceType: "consumer_survey",
    dateObserved: "2026-04-08",
    eventDate: "2026-04-02",
    region: "GCC",
    country: "Saudi Arabia",
    city: null,
    sectors: ["finance_banking_investment", "retail_commerce"],
    subsector: "consumer credit / BNPL",
    actorInvolved: "Regional BNPL providers and regulators (demo)",
    initialNotes:
      "Adoption and regulation are accelerating simultaneously — the interesting question is which arrives at scale first. Survey panel skews digital; treat magnitudes cautiously.",
    potentialFutureRelevance:
      "A regulated instalment layer could become the default credit on-ramp for Gulf youth, displacing cards and reshaping how banks acquire young customers.",
    status: "promoted",
    triageRationale: null,
    checklist: {
      behaviourShift: true,
      systemShift: true,
      surprising: false,
      widerRegionalIssue: true,
      credibleSource: true,
      futureImplications: true,
      connectedToOthers: true,
      revealsTension: true,
      earlyButMeaningful: false,
    },
    promotedSignalId: "SIG-009",
    createdAt: "2026-04-08T08:20:00.000Z",
    updatedAt: "2026-04-14T12:05:00.000Z",
  },

  // --- archived as noise -----------------------------------------------------
  {
    id: "OBS-007",
    title: "Global celebrity's mall appearance drives one-day social frenzy in Dubai",
    description:
      "A visiting global celebrity's appearance at a Dubai mall generated a one-day spike of creator content, queues and reposted clips across the TikTok panel, with several accounts framing it as evidence of Dubai's 'new cultural gravity'.",
    sourceId: "SRC-006",
    sourceName: "Regional TikTok fashion and lifestyle creators (demo panel)",
    sourceUrl: null,
    sourceType: "social_media",
    dateObserved: "2025-11-09",
    eventDate: "2025-11-08",
    region: "UAE",
    country: "UAE",
    city: "Dubai",
    sectors: ["retail_commerce", "media_entertainment_creator"],
    subsector: "celebrity retail activation",
    actorInvolved: "Global celebrity / mall operator (demo)",
    initialNotes: "High volume, zero persistence. Logged in case it recurs as a programming strategy.",
    potentialFutureRelevance:
      "None identified beyond routine event marketing; celebrity appearances have driven mall footfall spikes in the Gulf for two decades.",
    status: "archived_noise",
    triageRationale:
      "Attention spike, not behaviour change: the event produced a single day of amplified content with no repeat visitation, no new venue behaviour and no system consequence. The 'cultural gravity' framing came from accounts with a commercial stake in the activation. Fails novelty (celebrity mall appearances are an established Gulf retail tactic) and fails persistence. Archived as event-marketing noise; would only re-enter if appearance-led programming became a repeated repositioning strategy tied to dwell-time data.",
    checklist: {
      behaviourShift: false,
      systemShift: false,
      surprising: false,
      widerRegionalIssue: false,
      credibleSource: false,
      futureImplications: false,
      connectedToOthers: true,
      revealsTension: false,
      earlyButMeaningful: false,
    },
    promotedSignalId: null,
    createdAt: "2025-11-09T16:40:00.000Z",
    updatedAt: "2025-11-12T09:00:00.000Z",
  },
  {
    id: "OBS-008",
    title: "Influencer claims camel-milk skincare is 'going global' after single brand launch",
    description:
      "A wellness influencer on the panel declared camel-milk skincare the Gulf's next global export category after one small UAE brand announced a distribution deal. No sales data, no second brand, and search interest for the category is flat across the trend dashboard.",
    sourceId: "SRC-006",
    sourceName: "Regional TikTok fashion and lifestyle creators (demo panel)",
    sourceUrl: null,
    sourceType: "social_media",
    dateObserved: "2026-02-18",
    eventDate: "2026-02-15",
    region: "UAE",
    country: "UAE",
    city: "Dubai",
    sectors: ["health_wellness_longevity", "retail_commerce"],
    subsector: "beauty / skincare",
    actorInvolved: "Wellness influencer / small skincare brand (demo)",
    initialNotes: "Checked SRC-015: no movement in related search terms over 12 weeks.",
    potentialFutureRelevance:
      "Heritage-ingredient beauty is a plausible long-run theme, but this instance is a single-brand PR moment, not evidence of it.",
    status: "archived_noise",
    triageRationale:
      "Single anecdote amplified by a party with promotional interest: one brand, one deal, one influencer, and a flat search-trend line where genuine category formation would show movement. The underlying theme (heritage ingredients in premium beauty) stays on the watchlist, but this observation adds no evidence for it. Classic noise profile — high narrative confidence, zero corroboration. Would reconsider on a second independent brand launch or measurable search/sales momentum.",
    checklist: {
      behaviourShift: false,
      systemShift: false,
      surprising: true,
      widerRegionalIssue: false,
      credibleSource: false,
      futureImplications: false,
      connectedToOthers: false,
      revealsTension: false,
      earlyButMeaningful: false,
    },
    promotedSignalId: null,
    createdAt: "2026-02-18T14:10:00.000Z",
    updatedAt: "2026-02-20T08:35:00.000Z",
  },

  // --- needs more evidence ---------------------------------------------------
  {
    id: "OBS-009",
    title: "Trade piece reports Gulf employers piloting 'workcation' contracts for regional staff",
    description:
      "A single trade-publication article claims several Gulf employers are piloting contracts letting regional staff work from resort destinations for part of the year, framed as a retention tool for younger professionals. No employer is named on the record and no scheme details are provided.",
    sourceId: "SRC-003",
    sourceName: "GCC Hospitality Trade Review (demo)",
    sourceUrl: null,
    sourceType: "trade_publication",
    dateObserved: "2026-05-06",
    eventDate: "2026-04-28",
    region: "GCC",
    country: "UAE",
    city: null,
    sectors: ["education_work", "hospitality_tourism"],
    subsector: "flexible work / retention",
    actorInvolved: "Unnamed Gulf employers (demo)",
    initialNotes:
      "Plausible and consistent with the lifestyle-ecosystem cluster, but currently one anonymous trade story that hotels have an interest in circulating.",
    potentialFutureRelevance:
      "If real, blends the work and tourism systems and gives resorts a weekday-resident customer base.",
    status: "needs_more_evidence",
    triageRationale:
      "Held rather than promoted: a single weak source with unnamed actors and a clear commercial beneficiary (the hospitality trade press). The claimed behaviour would matter, so the observation stays open pending a second independent source — an employer statement, an HR survey datapoint, or booking-pattern evidence from operators. Review at next monthly triage.",
    checklist: {
      behaviourShift: true,
      systemShift: false,
      surprising: false,
      widerRegionalIssue: false,
      credibleSource: false,
      futureImplications: true,
      connectedToOthers: false,
      revealsTension: false,
      earlyButMeaningful: false,
    },
    promotedSignalId: null,
    createdAt: "2026-05-06T09:55:00.000Z",
    updatedAt: "2026-05-08T07:45:00.000Z",
  },

  // --- duplicate ---------------------------------------------------------------
  {
    id: "OBS-010",
    title: "Second operator announces resort longevity clinic in Riyadh",
    description:
      "Another Gulf operator announced a physician-led longevity and diagnostics clinic within a Riyadh resort property, with packaging and language closely mirroring the January Dubai announcement already captured in this inbox.",
    sourceId: "SRC-009",
    sourceName: "Press releases from a Gulf hotel and wellness operator (demo)",
    sourceUrl: null,
    sourceType: "company_announcement",
    dateObserved: "2026-02-03",
    eventDate: "2026-02-01",
    region: "Saudi Arabia",
    country: "Saudi Arabia",
    city: "Riyadh",
    sectors: ["hospitality_tourism", "health_wellness_longevity"],
    subsector: "wellness & longevity",
    actorInvolved: "Gulf resort operator (demo)",
    initialNotes: "Same underlying move as OBS-002; strengthens that signal rather than starting a new one.",
    potentialFutureRelevance:
      "Adds momentum evidence to the existing hotel-longevity signal; no distinct new behaviour or system.",
    status: "duplicate",
    triageRationale:
      "Duplicate of OBS-002: same behaviour (hotels adding clinical longevity infrastructure), same actor type, same framing, six weeks later. Rather than open a parallel entry, the announcement was folded into SIG-002 as corroborating momentum evidence. Kept on record so the momentum score for SIG-002 is traceable to more than one announcement.",
    checklist: {
      behaviourShift: true,
      systemShift: true,
      surprising: false,
      widerRegionalIssue: true,
      credibleSource: false,
      futureImplications: true,
      connectedToOthers: true,
      revealsTension: false,
      earlyButMeaningful: false,
    },
    promotedSignalId: null,
    createdAt: "2026-02-03T11:20:00.000Z",
    updatedAt: "2026-02-05T10:10:00.000Z",
  },

  // --- unreviewed --------------------------------------------------------------
  {
    id: "OBS-011",
    title: "Ramadan night economy formalising: extended licences and programmed night markets",
    description:
      "Field notes from Ramadan 2026 record municipalities extending late-night trading licences and staging programmed night markets in Riyadh and Sharjah, with retailers shifting staffing and delivery windows to a post-taraweeh peak that now runs past 02:00.",
    sourceId: "SRC-012",
    sourceName: "Analyst field notes from Riyadh and Jeddah coffee districts (demo)",
    sourceUrl: null,
    sourceType: "ethnographic_observation",
    dateObserved: "2026-03-10",
    eventDate: "2026-03-05",
    region: "GCC",
    country: "Saudi Arabia",
    city: "Riyadh",
    sectors: ["religion_ritual_ramadan", "retail_commerce", "food_beverage_third_places"],
    subsector: "night economy",
    actorInvolved: "Municipalities and retailers (demo)",
    initialNotes:
      "The night economy has always existed in Ramadan; what is new is its formalisation — licences, programming, staffing models. Candidate link to the lifestyle-ecosystem cluster.",
    potentialFutureRelevance:
      "A formalised seasonal night economy could reshape retail leases, labour scheduling and public-space programming beyond Ramadan itself.",
    status: "unreviewed",
    triageRationale: null,
    checklist: {
      behaviourShift: true,
      systemShift: true,
      surprising: false,
      widerRegionalIssue: true,
      credibleSource: false,
      futureImplications: true,
      connectedToOthers: true,
      revealsTension: false,
      earlyButMeaningful: true,
    },
    promotedSignalId: null,
    createdAt: "2026-03-10T21:00:00.000Z",
    updatedAt: "2026-03-10T21:00:00.000Z",
  },
  {
    id: "OBS-012",
    title: "GCC unified tourist visa discussions reported to be entering implementation planning",
    description:
      "Newspaper coverage of a GCC ministerial meeting reports that the long-discussed unified tourist visa has moved from principle to implementation planning, with officials describing multi-country itineraries as a target product for 2027 seasons.",
    sourceId: "SRC-004",
    sourceName: "Gulf economics desk of an international newspaper (demo)",
    sourceUrl: null,
    sourceType: "news_publication",
    dateObserved: "2026-06-15",
    eventDate: "2026-06-11",
    region: "GCC",
    country: "Saudi Arabia",
    city: null,
    sectors: ["hospitality_tourism", "government_policy"],
    subsector: "visa policy",
    actorInvolved: "GCC tourism ministries (demo)",
    initialNotes:
      "Repeated announcements without dates have been the pattern since 2023; implementation-planning language is the new element. Watch for a published timeline.",
    potentialFutureRelevance:
      "A single Gulf tourism space would push destination strategies from national competition towards itinerary-based cooperation.",
    status: "unreviewed",
    triageRationale: null,
    checklist: {
      behaviourShift: false,
      systemShift: true,
      surprising: false,
      widerRegionalIssue: true,
      credibleSource: true,
      futureImplications: true,
      connectedToOthers: false,
      revealsTension: false,
      earlyButMeaningful: false,
    },
    promotedSignalId: null,
    createdAt: "2026-06-15T08:30:00.000Z",
    updatedAt: "2026-06-15T08:30:00.000Z",
  },
  {
    id: "OBS-013",
    title: "Padel courts and run clubs multiplying as Riyadh's default social plan",
    description:
      "Panel creators in Riyadh increasingly document padel bookings and early-morning run clubs as the default social plan, with venues reporting booked-out courts weeks ahead and run clubs partnering with coffee houses for post-run gatherings.",
    sourceId: "SRC-006",
    sourceName: "Regional TikTok fashion and lifestyle creators (demo panel)",
    sourceUrl: null,
    sourceType: "social_media",
    dateObserved: "2026-05-18",
    eventDate: null,
    region: "Saudi Arabia",
    country: "Saudi Arabia",
    city: "Riyadh",
    sectors: ["sports_gaming", "health_wellness_longevity", "food_beverage_third_places"],
    subsector: "social sport",
    actorInvolved: "Padel venues, run clubs, coffee houses (demo)",
    initialNotes:
      "Reads as an extension of the third-places behaviour into active formats. Needs a non-social-media source before promotion.",
    potentialFutureRelevance:
      "Social sport as community infrastructure — relevant to developers, malls and wellness brands programming for young Saudis.",
    status: "unreviewed",
    triageRationale: null,
    checklist: {
      behaviourShift: true,
      systemShift: false,
      surprising: false,
      widerRegionalIssue: true,
      credibleSource: false,
      futureImplications: true,
      connectedToOthers: true,
      revealsTension: false,
      earlyButMeaningful: true,
    },
    promotedSignalId: null,
    createdAt: "2026-05-18T17:25:00.000Z",
    updatedAt: "2026-05-18T17:25:00.000Z",
  },
  {
    id: "OBS-014",
    title: "Cultural producer reports Saudisation quotas reshaping creative-sector hiring",
    description:
      "In interview, the Riyadh-based cultural producer described commissioning bodies and production companies restructuring teams to meet Saudisation targets in creative roles, accelerating salaries for experienced Saudi producers and creating a training bottleneck for technical crafts.",
    sourceId: "SRC-008",
    sourceName: "Interview with a Riyadh-based cultural producer (demo)",
    sourceUrl: null,
    sourceType: "expert_interview",
    dateObserved: "2026-04-22",
    eventDate: null,
    region: "Saudi Arabia",
    country: "Saudi Arabia",
    city: "Riyadh",
    sectors: ["education_work", "culture_arts_heritage", "government_policy"],
    subsector: "creative labour market",
    actorInvolved: "Commissioning bodies and production companies (demo)",
    initialNotes:
      "Single vantage point but a credible one; consistent with the state-led cultural-investment signal. Check for wage or vacancy data before promotion.",
    potentialFutureRelevance:
      "Labour policy is deciding who gets to make Saudi culture — with long-run consequences for the creative economy's depth and voice.",
    status: "unreviewed",
    triageRationale: null,
    checklist: {
      behaviourShift: true,
      systemShift: true,
      surprising: false,
      widerRegionalIssue: true,
      credibleSource: true,
      futureImplications: true,
      connectedToOthers: true,
      revealsTension: true,
      earlyButMeaningful: false,
    },
    promotedSignalId: null,
    createdAt: "2026-04-22T15:40:00.000Z",
    updatedAt: "2026-04-22T15:40:00.000Z",
  },
  {
    id: "OBS-015",
    title: "Mall operators converting car-park levels to EV charging and last-mile logistics hubs",
    description:
      "Trade coverage describes two regional mall operators converting lower car-park levels into EV charging plazas and quick-commerce fulfilment space, citing falling private-car dwell times near new transit stations and rising delivery volumes.",
    sourceId: "SRC-003",
    sourceName: "GCC Hospitality Trade Review (demo)",
    sourceUrl: null,
    sourceType: "trade_publication",
    dateObserved: "2026-05-02",
    eventDate: "2026-04-25",
    region: "GCC",
    country: "UAE",
    city: "Dubai",
    sectors: ["climate_energy_environment", "retail_commerce", "mobility_transport"],
    subsector: "mall infrastructure",
    actorInvolved: "Regional mall operators (demo)",
    initialNotes:
      "Interesting second-order echo of both the transit signal and the mall-repositioning signal — parking as the first asset class disrupted by both.",
    potentialFutureRelevance:
      "Car-park conversion is a leading indicator of how seriously operators take the post-car-dependence scenario.",
    status: "unreviewed",
    triageRationale: null,
    checklist: {
      behaviourShift: false,
      systemShift: true,
      surprising: true,
      widerRegionalIssue: true,
      credibleSource: false,
      futureImplications: true,
      connectedToOthers: true,
      revealsTension: false,
      earlyButMeaningful: true,
    },
    promotedSignalId: null,
    createdAt: "2026-05-02T10:05:00.000Z",
    updatedAt: "2026-05-02T10:05:00.000Z",
  },
  {
    id: "OBS-016",
    title: "Telecom operator launches Arabic voice assistant tuned to Gulf dialects",
    description:
      "A regional telecom operator announced a consumer voice assistant trained on Gulf Arabic dialects, marketed explicitly on the promise that customers 'should not have to speak like a machine — or in English — to be understood', with early deployment in customer service lines.",
    sourceId: null,
    sourceName: "Regional telecom operator product announcement (demo)",
    sourceUrl: null,
    sourceType: "company_announcement",
    dateObserved: "2026-06-28",
    eventDate: "2026-06-24",
    region: "GCC",
    country: "Saudi Arabia",
    city: null,
    sectors: ["technology_ai", "media_entertainment_creator"],
    subsector: "Arabic language technology",
    actorInvolved: "Regional telecom operator (demo)",
    initialNotes:
      "Dialect-first positioning is the notable part — language identity used as a trust and differentiation claim in AI products. Possible link to both the AI-trust signal and the regional-identity cluster.",
    potentialFutureRelevance:
      "If dialect competence becomes a baseline expectation, global AI products face a localisation bar that regional players can weaponise.",
    status: "unreviewed",
    triageRationale: null,
    checklist: {
      behaviourShift: false,
      systemShift: false,
      surprising: true,
      widerRegionalIssue: true,
      credibleSource: false,
      futureImplications: true,
      connectedToOthers: true,
      revealsTension: true,
      earlyButMeaningful: true,
    },
    promotedSignalId: null,
    createdAt: "2026-06-28T09:15:00.000Z",
    updatedAt: "2026-06-28T09:15:00.000Z",
  },
];
