/**
 * Demo observations — the Scan Inbox layer.
 *
 * Statuses are mixed deliberately: six promoted (each pointing at the signal
 * it became), two archived as noise with explicit triage rationales for the
 * Noise Filter panel, one parked for more evidence, one duplicate, and six
 * still unreviewed. Checklists are filled consistently with each status.
 */

import type { Observation } from "../types";

export const seedObservations: Observation[] = [
  // --- promoted ------------------------------------------------------------
  {
    id: "OBS-001",
    title: "Gulf menswear labels are redesigning the thobe for daily wear",
    description:
      "Through September 2025, the TikTok creator panel repeatedly surfaced small menswear labels in Dubai and Riyadh releasing redesigned thobes and bishts. The pieces use technical fabrics, shortened hems, hidden plackets and sneaker-first styling. Creators presented them as everyday wear, not occasion dress. Several drops sold out within days.",
    sourceId: "SRC-006",
    sourceName: "Regional TikTok fashion and lifestyle creators (demo panel)",
    sourceUrl: null,
    sourceType: "social_media",
    dateObserved: "2025-09-29",
    eventDate: "2025-09-20",
    region: "GCC",
    country: "UAE",
    city: "Dubai",
    sectors: ["fashion_luxury", "culture_arts_heritage"],
    subsector: "menswear / contemporary heritage design",
    actorInvolved: "Independent regional menswear labels (demo)",
    initialNotes:
      "This is not a costume revival. The design language is contemporary, and prices sit between streetwear and entry-level luxury. Several labels are moving at once, and a culture magazine has since profiled two of them.",
    potentialFutureRelevance:
      "If heritage garments become everyday design rather than ceremonial dress, regional identity becomes something fashion, retail and media businesses can build on.",
    status: "promoted",
    triageRationale: null,
    checklist: {
      behaviourShift: true,
      systemShift: false,
      surprising: true,
      widerRegionalIssue: true,
      credibleSource: false,
      futureImplications: true,
      connectedToOthers: true,
      revealsTension: true,
      earlyButMeaningful: true,
    },
    promotedSignalId: "SIG-001",
    createdAt: "2025-09-29T10:15:00.000Z",
    updatedAt: "2025-10-06T08:40:00.000Z",
  },
  {
    id: "OBS-002",
    title: "Gulf resort operator announces in-house longevity clinic with diagnostics",
    description:
      "A regional hotel and wellness operator announced a longevity clinic inside a flagship Dubai resort. It offers full-body diagnostic screening, biomarker panels and physician-led programmes sold as multi-day packages. The release presents the clinic as a permanent facility, not a seasonal retreat, and names a second property in Riyadh for 2026.",
    sourceId: "SRC-009",
    sourceName: "Press releases from a Gulf hotel and wellness operator (demo)",
    sourceUrl: null,
    sourceType: "company_announcement",
    dateObserved: "2026-01-14",
    eventDate: "2026-01-12",
    region: "UAE",
    country: "UAE",
    city: "Dubai",
    sectors: ["hospitality_tourism", "health_wellness_longevity"],
    subsector: "wellness & longevity",
    actorInvolved: "Gulf hotel and wellness operator (demo)",
    initialNotes:
      "This is the third such announcement logged since November. Trade press reports two more operators looking for clinical partners. The source is heavy on PR, but the pattern of real spending is there.",
    potentialFutureRelevance:
      "Hotels adding clinics blur the line between hospitality and healthcare. They give the Gulf a claim on fly-in longevity customers currently served by Switzerland and Southeast Asia.",
    status: "promoted",
    triageRationale: null,
    checklist: {
      behaviourShift: true,
      systemShift: true,
      surprising: true,
      widerRegionalIssue: true,
      credibleSource: false,
      futureImplications: true,
      connectedToOthers: true,
      revealsTension: false,
      earlyButMeaningful: true,
    },
    promotedSignalId: "SIG-002",
    createdAt: "2026-01-14T09:05:00.000Z",
    updatedAt: "2026-01-20T11:30:00.000Z",
  },
  {
    id: "OBS-003",
    title: "Golden-visa families are lengthening school waiting lists in Dubai",
    description:
      "Newspaper reporting, backed by school-group statements, describes growing waiting lists at mid-fee British- and Indian-curriculum schools in Dubai's family districts. Schools attribute the pressure to households relocating on 10-year golden visas. Letting agents report more three-bedroom renewals and families asking for longer tenancies.",
    sourceId: "SRC-004",
    sourceName: "Gulf economics desk of an international newspaper (demo)",
    sourceUrl: null,
    sourceType: "news_publication",
    dateObserved: "2025-10-27",
    eventDate: "2025-10-20",
    region: "UAE",
    country: "UAE",
    city: "Dubai",
    sectors: ["migration_citizenship_belonging", "real_estate_urban", "education_work"],
    subsector: "long-term residency",
    actorInvolved: "Relocating families on long-term visas (demo)",
    initialNotes:
      "The interesting unit is the family, not the worker. School enrolment and multi-year leases are commitments that a model built around people leaving after a few years does not produce.",
    potentialFutureRelevance:
      "Residency policy is turning a market of rotating workers into a market of settling families, with structural consequences for housing mix, school capacity and household finance.",
    status: "promoted",
    triageRationale: null,
    checklist: {
      behaviourShift: true,
      systemShift: true,
      surprising: false,
      widerRegionalIssue: true,
      credibleSource: true,
      futureImplications: true,
      connectedToOthers: true,
      revealsTension: true,
      earlyButMeaningful: true,
    },
    promotedSignalId: "SIG-003",
    createdAt: "2025-10-27T07:50:00.000Z",
    updatedAt: "2025-11-05T09:10:00.000Z",
  },
  {
    id: "OBS-004",
    title: "Equity note: bank customers want humans to confirm AI decisions",
    description:
      "A regional investment-bank note on Gulf retail banks describes fast deployment of AI assistants and automated credit decisions. It then flags an unexpected datapoint: branch appointments and complaints are rising as customers ask for human confirmation of AI-made decisions. Youth survey verbatims echo the same demand.",
    sourceId: "SRC-013",
    sourceName: "Gulf banking sector note from a regional investment bank (demo)",
    sourceUrl: null,
    sourceType: "financial_research",
    dateObserved: "2026-03-02",
    eventDate: "2026-02-25",
    region: "GCC",
    country: "UAE",
    city: null,
    sectors: ["technology_ai", "finance_banking_investment"],
    subsector: "retail banking automation",
    actorInvolved: "Gulf retail banks (demo)",
    initialNotes:
      "The automation is expected; the countercurrent is not. Customers are not rejecting AI — they want a person layered on top of it. That is a product gap, not a resistance story.",
    potentialFutureRelevance:
      "If the demand persists, 'a person will confirm this' becomes a sellable service tier across banking, insurance and government services.",
    status: "promoted",
    triageRationale: null,
    checklist: {
      behaviourShift: true,
      systemShift: true,
      surprising: true,
      widerRegionalIssue: true,
      credibleSource: true,
      futureImplications: true,
      connectedToOthers: true,
      revealsTension: true,
      earlyButMeaningful: true,
    },
    promotedSignalId: "SIG-006",
    createdAt: "2026-03-02T13:25:00.000Z",
    updatedAt: "2026-03-09T10:00:00.000Z",
  },
  {
    id: "OBS-005",
    title: "Field notes: Riyadh coffee houses serve as evening gathering places",
    description:
      "Across six observation visits in Riyadh and Jeddah, specialty coffee houses were consistently full from 20:00 to past midnight. Groups were studying, running book clubs, holding small-business meetings and gathering informally, majlis-style. Several venues now programme events and reserve tables for regular groups.",
    sourceId: "SRC-012",
    sourceName: "Analyst field notes from Riyadh and Jeddah coffee districts (demo)",
    sourceUrl: null,
    sourceType: "ethnographic_observation",
    dateObserved: "2025-10-16",
    eventDate: null,
    region: "Saudi Arabia",
    country: "Saudi Arabia",
    city: "Riyadh",
    sectors: ["food_beverage_third_places", "culture_arts_heritage"],
    subsector: "specialty coffee / third places",
    actorInvolved: "Independent specialty coffee houses (demo)",
    initialNotes:
      "The venues behave like community infrastructure, not food-and-drink outlets: repeat groups, programmed events, long stays and low table turnover that operators accept. A cultural producer interviewed confirms the venues are becoming the default meeting places for young creatives.",
    potentialFutureRelevance:
      "Young people are building gathering places before formal civic infrastructure exists. Whoever hosts them shapes community, taste and spending for a decade.",
    status: "promoted",
    triageRationale: null,
    checklist: {
      behaviourShift: true,
      systemShift: true,
      surprising: false,
      widerRegionalIssue: true,
      credibleSource: false,
      futureImplications: true,
      connectedToOthers: true,
      revealsTension: false,
      earlyButMeaningful: true,
    },
    promotedSignalId: "SIG-008",
    createdAt: "2025-10-16T18:45:00.000Z",
    updatedAt: "2025-10-19T09:30:00.000Z",
  },
  {
    id: "OBS-006",
    title: "Youth survey shows buy-now-pay-later habit; regulator signals tighter licensing",
    description:
      "The quarterly GCC youth survey reports that most Saudi 18–30 respondents use buy-now-pay-later at least monthly. A growing share carries three or more plans at once. In the same fortnight, the financial press reported central-bank commentary signalling tighter licensing and affordability rules for instalment providers.",
    sourceId: "SRC-011",
    sourceName: "GCC youth financial habits survey by a regional research house (demo)",
    sourceUrl: null,
    sourceType: "consumer_survey",
    dateObserved: "2026-04-08",
    eventDate: "2026-04-02",
    region: "GCC",
    country: "Saudi Arabia",
    city: null,
    sectors: ["finance_banking_investment", "retail_commerce"],
    subsector: "consumer credit / BNPL",
    actorInvolved: "Regional BNPL providers and regulators (demo)",
    initialNotes:
      "Use and regulation are accelerating at the same time; the interesting question is which reaches scale first. The survey panel skews digital, so treat the exact numbers cautiously.",
    potentialFutureRelevance:
      "A regulated instalment layer could become the standard first credit product for Gulf youth, displacing cards and changing how banks win young customers.",
    status: "promoted",
    triageRationale: null,
    checklist: {
      behaviourShift: true,
      systemShift: true,
      surprising: false,
      widerRegionalIssue: true,
      credibleSource: true,
      futureImplications: true,
      connectedToOthers: true,
      revealsTension: true,
      earlyButMeaningful: false,
    },
    promotedSignalId: "SIG-009",
    createdAt: "2026-04-08T08:20:00.000Z",
    updatedAt: "2026-04-14T12:05:00.000Z",
  },

  // --- archived as noise -----------------------------------------------------
  {
    id: "OBS-007",
    title: "Celebrity mall visit in Dubai causes one-day social media spike",
    description:
      "A visiting global celebrity appeared at a Dubai mall. The TikTok panel showed one day of creator content, queues and reposted clips. Several accounts framed the event as proof of Dubai's 'new cultural gravity'.",
    sourceId: "SRC-006",
    sourceName: "Regional TikTok fashion and lifestyle creators (demo panel)",
    sourceUrl: null,
    sourceType: "social_media",
    dateObserved: "2025-11-09",
    eventDate: "2025-11-08",
    region: "UAE",
    country: "UAE",
    city: "Dubai",
    sectors: ["retail_commerce", "media_entertainment_creator"],
    subsector: "celebrity retail activation",
    actorInvolved: "Global celebrity / mall operator (demo)",
    initialNotes: "High volume, zero persistence. Logged in case it recurs as a programming strategy.",
    potentialFutureRelevance:
      "None identified beyond routine event marketing. Celebrity appearances have driven mall footfall spikes in the Gulf for two decades.",
    status: "archived_noise",
    triageRationale:
      "An attention spike, not a behaviour change. The event produced one day of amplified content with no repeat visits, no new venue behaviour and no system consequence. The 'cultural gravity' framing came from accounts with a commercial stake in the event. Celebrity mall appearances are an established Gulf retail tactic, so the observation fails on novelty and fails on persistence. Archived as event-marketing noise. It would re-enter only if appearance-led programming became a repeated repositioning strategy backed by dwell-time data.",
    checklist: {
      behaviourShift: false,
      systemShift: false,
      surprising: false,
      widerRegionalIssue: false,
      credibleSource: false,
      futureImplications: false,
      connectedToOthers: true,
      revealsTension: false,
      earlyButMeaningful: false,
    },
    promotedSignalId: null,
    createdAt: "2025-11-09T16:40:00.000Z",
    updatedAt: "2025-11-12T09:00:00.000Z",
  },
  {
    id: "OBS-008",
    title: "Influencer claims camel-milk skincare is 'going global' after single brand launch",
    description:
      "A wellness influencer on the panel declared camel-milk skincare the Gulf's next global export after one small UAE brand announced a distribution deal. There is no sales data and no second brand. Search interest in the category is flat on the trend dashboard.",
    sourceId: "SRC-006",
    sourceName: "Regional TikTok fashion and lifestyle creators (demo panel)",
    sourceUrl: null,
    sourceType: "social_media",
    dateObserved: "2026-02-18",
    eventDate: "2026-02-15",
    region: "UAE",
    country: "UAE",
    city: "Dubai",
    sectors: ["health_wellness_longevity", "retail_commerce"],
    subsector: "beauty / skincare",
    actorInvolved: "Wellness influencer / small skincare brand (demo)",
    initialNotes: "Checked SRC-015: no movement in related search terms over 12 weeks.",
    potentialFutureRelevance:
      "Heritage-ingredient beauty is a plausible long-term theme. This instance is a single brand's PR moment, not evidence for it.",
    status: "archived_noise",
    triageRationale:
      "A single anecdote amplified by someone with a promotional interest: one brand, one deal, one influencer. Search trends are flat where a real new category would show movement. The underlying theme — heritage ingredients in premium beauty — stays on the watchlist, but this observation adds no evidence for it. It has the classic noise profile: high narrative confidence, zero corroboration. We would reconsider if a second independent brand launched, or if search or sales data moved.",
    checklist: {
      behaviourShift: false,
      systemShift: false,
      surprising: true,
      widerRegionalIssue: false,
      credibleSource: false,
      futureImplications: false,
      connectedToOthers: false,
      revealsTension: false,
      earlyButMeaningful: false,
    },
    promotedSignalId: null,
    createdAt: "2026-02-18T14:10:00.000Z",
    updatedAt: "2026-02-20T08:35:00.000Z",
  },

  // --- needs more evidence ---------------------------------------------------
  {
    id: "OBS-009",
    title: "Trade article claims Gulf employers are piloting 'workcation' contracts",
    description:
      "A single trade article claims several Gulf employers are piloting contracts that let regional staff work from resort destinations for part of the year. The framing is staff retention for younger professionals. No employer is named on the record, and no scheme details are given.",
    sourceId: "SRC-003",
    sourceName: "GCC Hospitality Trade Review (demo)",
    sourceUrl: null,
    sourceType: "trade_publication",
    dateObserved: "2026-05-06",
    eventDate: "2026-04-28",
    region: "GCC",
    country: "UAE",
    city: null,
    sectors: ["education_work", "hospitality_tourism"],
    subsector: "flexible work / retention",
    actorInvolved: "Unnamed Gulf employers (demo)",
    initialNotes:
      "Plausible, and consistent with the lifestyle-ecosystem cluster. But it is one anonymous trade story, and hotels have an interest in circulating it.",
    potentialFutureRelevance:
      "If real, it blends work and tourism and gives resorts a weekday customer base of working residents.",
    status: "needs_more_evidence",
    triageRationale:
      "Held rather than promoted. This is a single weak source with unnamed actors, and the hospitality trade press benefits commercially from the story. The claimed behaviour would matter, so the observation stays open. It needs a second independent source: an employer statement, an HR survey datapoint, or booking-pattern evidence from operators. Review at the next monthly triage.",
    checklist: {
      behaviourShift: true,
      systemShift: false,
      surprising: false,
      widerRegionalIssue: false,
      credibleSource: false,
      futureImplications: true,
      connectedToOthers: false,
      revealsTension: false,
      earlyButMeaningful: false,
    },
    promotedSignalId: null,
    createdAt: "2026-05-06T09:55:00.000Z",
    updatedAt: "2026-05-08T07:45:00.000Z",
  },

  // --- duplicate ---------------------------------------------------------------
  {
    id: "OBS-010",
    title: "Second operator announces resort longevity clinic in Riyadh",
    description:
      "Another Gulf operator announced a physician-led longevity and diagnostics clinic inside a Riyadh resort. The packaging and language closely mirror the January Dubai announcement already captured in this inbox.",
    sourceId: "SRC-009",
    sourceName: "Press releases from a Gulf hotel and wellness operator (demo)",
    sourceUrl: null,
    sourceType: "company_announcement",
    dateObserved: "2026-02-03",
    eventDate: "2026-02-01",
    region: "Saudi Arabia",
    country: "Saudi Arabia",
    city: "Riyadh",
    sectors: ["hospitality_tourism", "health_wellness_longevity"],
    subsector: "wellness & longevity",
    actorInvolved: "Gulf resort operator (demo)",
    initialNotes: "Same underlying move as OBS-002. It strengthens that signal rather than starting a new one.",
    potentialFutureRelevance:
      "Adds momentum evidence to the existing hotel-longevity signal. No distinct new behaviour or system.",
    status: "duplicate",
    triageRationale:
      "Duplicate of OBS-002: the same behaviour (hotels adding longevity clinics), the same actor type and the same framing, six weeks later. Rather than open a parallel entry, we folded the announcement into SIG-002 as corroborating momentum evidence. It stays on record so SIG-002's momentum score can be traced to more than one announcement.",
    checklist: {
      behaviourShift: true,
      systemShift: true,
      surprising: false,
      widerRegionalIssue: true,
      credibleSource: false,
      futureImplications: true,
      connectedToOthers: true,
      revealsTension: false,
      earlyButMeaningful: false,
    },
    promotedSignalId: null,
    createdAt: "2026-02-03T11:20:00.000Z",
    updatedAt: "2026-02-05T10:10:00.000Z",
  },

  // --- unreviewed --------------------------------------------------------------
  {
    id: "OBS-011",
    title: "Cities are formalising the Ramadan night economy with licences and markets",
    description:
      "Field notes from Ramadan 2026 record municipalities in Riyadh and Sharjah extending late-night trading licences and staging programmed night markets. Retailers are shifting staffing and delivery windows to a peak that starts after taraweeh prayers and now runs past 02:00.",
    sourceId: "SRC-012",
    sourceName: "Analyst field notes from Riyadh and Jeddah coffee districts (demo)",
    sourceUrl: null,
    sourceType: "ethnographic_observation",
    dateObserved: "2026-03-10",
    eventDate: "2026-03-05",
    region: "GCC",
    country: "Saudi Arabia",
    city: "Riyadh",
    sectors: ["religion_ritual_ramadan", "retail_commerce", "food_beverage_third_places"],
    subsector: "night economy",
    actorInvolved: "Municipalities and retailers (demo)",
    initialNotes:
      "Ramadan has always had a night economy. What is new is the formal structure: licences, programmed events, staffing models. Candidate link to the lifestyle-ecosystem cluster.",
    potentialFutureRelevance:
      "A formal seasonal night economy could reshape retail leases, work schedules and public-space programming beyond Ramadan itself.",
    status: "unreviewed",
    triageRationale: null,
    checklist: {
      behaviourShift: true,
      systemShift: true,
      surprising: false,
      widerRegionalIssue: true,
      credibleSource: false,
      futureImplications: true,
      connectedToOthers: true,
      revealsTension: false,
      earlyButMeaningful: true,
    },
    promotedSignalId: null,
    createdAt: "2026-03-10T21:00:00.000Z",
    updatedAt: "2026-03-10T21:00:00.000Z",
  },
  {
    id: "OBS-012",
    title: "GCC unified tourist visa reportedly moving to implementation planning",
    description:
      "Newspaper coverage of a GCC ministerial meeting reports that the long-discussed unified tourist visa has moved from principle to implementation planning. Officials describe multi-country itineraries as a target product for the 2027 seasons.",
    sourceId: "SRC-004",
    sourceName: "Gulf economics desk of an international newspaper (demo)",
    sourceUrl: null,
    sourceType: "news_publication",
    dateObserved: "2026-06-15",
    eventDate: "2026-06-11",
    region: "GCC",
    country: "Saudi Arabia",
    city: null,
    sectors: ["hospitality_tourism", "government_policy"],
    subsector: "visa policy",
    actorInvolved: "GCC tourism ministries (demo)",
    initialNotes:
      "Announcements without dates have been the pattern since 2023. The implementation-planning language is the new element. Watch for a published timeline.",
    potentialFutureRelevance:
      "A shared Gulf tourist visa could make countries plan trips together instead of only competing for visitors separately.",
    status: "unreviewed",
    triageRationale: null,
    checklist: {
      behaviourShift: false,
      systemShift: true,
      surprising: false,
      widerRegionalIssue: true,
      credibleSource: true,
      futureImplications: true,
      connectedToOthers: false,
      revealsTension: false,
      earlyButMeaningful: false,
    },
    promotedSignalId: null,
    createdAt: "2026-06-15T08:30:00.000Z",
    updatedAt: "2026-06-15T08:30:00.000Z",
  },
  {
    id: "OBS-013",
    title: "Padel and run clubs are becoming Riyadh's default social plan",
    description:
      "Panel creators in Riyadh increasingly document padel bookings and early-morning run clubs as the default social plan. Venues report courts booked out weeks ahead. Run clubs are partnering with coffee houses for post-run gatherings.",
    sourceId: "SRC-006",
    sourceName: "Regional TikTok fashion and lifestyle creators (demo panel)",
    sourceUrl: null,
    sourceType: "social_media",
    dateObserved: "2026-05-18",
    eventDate: null,
    region: "Saudi Arabia",
    country: "Saudi Arabia",
    city: "Riyadh",
    sectors: ["sports_gaming", "health_wellness_longevity", "food_beverage_third_places"],
    subsector: "social sport",
    actorInvolved: "Padel venues, run clubs, coffee houses (demo)",
    initialNotes:
      "This extends the coffee-house gathering behaviour into active formats. It needs a source beyond social media before promotion.",
    potentialFutureRelevance:
      "Social sport is becoming community infrastructure. That matters to developers, malls and wellness brands programming for young Saudis.",
    status: "unreviewed",
    triageRationale: null,
    checklist: {
      behaviourShift: true,
      systemShift: false,
      surprising: false,
      widerRegionalIssue: true,
      credibleSource: false,
      futureImplications: true,
      connectedToOthers: true,
      revealsTension: false,
      earlyButMeaningful: true,
    },
    promotedSignalId: null,
    createdAt: "2026-05-18T17:25:00.000Z",
    updatedAt: "2026-05-18T17:25:00.000Z",
  },
  {
    id: "OBS-014",
    title: "Cultural producer reports Saudisation quotas reshaping creative-sector hiring",
    description:
      "In an interview, a Riyadh-based cultural producer described commissioning bodies and production companies restructuring teams to meet Saudisation targets in creative roles. Salaries for experienced Saudi producers are rising fast, and technical crafts face a training bottleneck.",
    sourceId: "SRC-008",
    sourceName: "Interview with a Riyadh-based cultural producer (demo)",
    sourceUrl: null,
    sourceType: "expert_interview",
    dateObserved: "2026-04-22",
    eventDate: null,
    region: "Saudi Arabia",
    country: "Saudi Arabia",
    city: "Riyadh",
    sectors: ["education_work", "culture_arts_heritage", "government_policy"],
    subsector: "creative labour market",
    actorInvolved: "Commissioning bodies and production companies (demo)",
    initialNotes:
      "A single vantage point, but a credible one, and consistent with the state-led cultural-investment signal. Check wage or vacancy data before promotion.",
    potentialFutureRelevance:
      "Labour policy is deciding who gets to make Saudi culture, with long-term consequences for the creative economy's depth and voice.",
    status: "unreviewed",
    triageRationale: null,
    checklist: {
      behaviourShift: true,
      systemShift: true,
      surprising: false,
      widerRegionalIssue: true,
      credibleSource: true,
      futureImplications: true,
      connectedToOthers: true,
      revealsTension: true,
      earlyButMeaningful: false,
    },
    promotedSignalId: null,
    createdAt: "2026-04-22T15:40:00.000Z",
    updatedAt: "2026-04-22T15:40:00.000Z",
  },
  {
    id: "OBS-015",
    title: "Mall operators are converting car parks to EV charging and delivery hubs",
    description:
      "Trade coverage describes two regional mall operators converting lower car-park levels into EV charging plazas and quick-commerce fulfilment space. They cite shorter private-car stays near new transit stations and rising delivery volumes.",
    sourceId: "SRC-003",
    sourceName: "GCC Hospitality Trade Review (demo)",
    sourceUrl: null,
    sourceType: "trade_publication",
    dateObserved: "2026-05-02",
    eventDate: "2026-04-25",
    region: "GCC",
    country: "UAE",
    city: "Dubai",
    sectors: ["climate_energy_environment", "retail_commerce", "mobility_transport"],
    subsector: "mall infrastructure",
    actorInvolved: "Regional mall operators (demo)",
    initialNotes:
      "An interesting second-order echo of both the transit signal and the mall-repositioning signal. Parking is the first asset both disrupt.",
    potentialFutureRelevance:
      "Car-park conversion shows how seriously operators take a future with less car dependence.",
    status: "unreviewed",
    triageRationale: null,
    checklist: {
      behaviourShift: false,
      systemShift: true,
      surprising: true,
      widerRegionalIssue: true,
      credibleSource: false,
      futureImplications: true,
      connectedToOthers: true,
      revealsTension: false,
      earlyButMeaningful: true,
    },
    promotedSignalId: null,
    createdAt: "2026-05-02T10:05:00.000Z",
    updatedAt: "2026-05-02T10:05:00.000Z",
  },
  {
    id: "OBS-016",
    title: "Telecom operator launches Arabic voice assistant tuned to Gulf dialects",
    description:
      "A regional telecom operator announced a consumer voice assistant trained on Gulf Arabic dialects. Marketing leads with the promise that customers 'should not have to speak like a machine — or in English — to be understood'. Early deployment is in customer service lines.",
    sourceId: null,
    sourceName: "Regional telecom operator product announcement (demo)",
    sourceUrl: null,
    sourceType: "company_announcement",
    dateObserved: "2026-06-28",
    eventDate: "2026-06-24",
    region: "GCC",
    country: "Saudi Arabia",
    city: null,
    sectors: ["technology_ai", "media_entertainment_creator"],
    subsector: "Arabic language technology",
    actorInvolved: "Regional telecom operator (demo)",
    initialNotes:
      "The dialect-first positioning is the notable part: language identity used as a trust and differentiation claim in an AI product. Possible link to both the AI-trust signal and the regional-identity cluster.",
    potentialFutureRelevance:
      "If dialect competence becomes a baseline expectation, global AI products face a localisation bar that regional players can use against them.",
    status: "unreviewed",
    triageRationale: null,
    checklist: {
      behaviourShift: false,
      systemShift: false,
      surprising: true,
      widerRegionalIssue: true,
      credibleSource: false,
      futureImplications: true,
      connectedToOthers: true,
      revealsTension: true,
      earlyButMeaningful: true,
    },
    promotedSignalId: null,
    createdAt: "2026-06-28T09:15:00.000Z",
    updatedAt: "2026-06-28T09:15:00.000Z",
  },
];
